CREATE TABLE MAINTANANCE_TASKS(
        TASK_ID INTEGER NOT NULL PRIMARY KEY,
        ENGINEER_ID INTEGER NOT NULL,
        DEVICE_INVOICE_ID INTEGER NOT NULL,
        FAULT_DESCRIPTION VARCHAR(512) DEFAULT ' ' NOT NULL,
        CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        DUE_DATE TIMESTAMP NOT NULL);


CREATE TABLE REPORTING_EVENTS(
        REQUEST_CORELATOR VARCHAR(50) NOT NULL PRIMARY KEY,
        OPERATION_NAME VARCHAR(50) NOT NULL,
        RECORDED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        REQUEST VARCHAR(1024) NOT NULL,
        RESPONSE VARCHAR(1024) NOT NULL);

